# Collaborative Filtering
협업 필터링은 최근접 이웃 협업 필터링과 잠재 요인 협업 필터링으로 나뉘고,    
최근접 이웃 협업 필터링은 다시 유저 기반과 아이템 기반으로 나뉜다.   
맥주 추천의 경우 유저의 취향은 너무 다양한 데 비해, 리뷰를 남기는 맥주의 수는 한정적이므로 아이템 기반 추천을 사용해본다.

In [1]:
import pandas as pd
import numpy as np

from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics import mean_squared_error

import warnings
warnings.filterwarnings('ignore')

In [16]:
data = pd.read_csv('beer_final.csv', index_col=0)

### 데이터 정제
최소 n개 이상의 리뷰를 가진 맥주, 유저들의 데이터셋 구성

In [14]:
data

,검색이름,유저,맥주이름,평점,Aroma,Appearance,Flavor,Mouthfeel,Overall
0,kloud,68931,Kloud Original Gravity,2.8,5,3,5,3,12
1,kloud,236424,Kloud Original Gravity,3.9,10,5,10,5,9
2,kloud,606,Kloud Original Gravity,2.4,6,3,4,2,9
3,kloud,151390,Kloud Original Gravity,2.3,4,3,4,3,9
4,kloud,334131,Kloud Original Gravity,1.0,1,1,1,1,6
...,...,...,...,...,...,...,...,...,...
54650,Red Rock,15921,Red Rock,2.2,5,3,4,2,8
54651,Red Rock,32788,Red Rock,1.4,2,3,3,3,3
54652,Red Rock,8771,Red Rock,1.1,2,2,2,1,4
54653,Red Rock,7208,Red Rock,1.2,2,3,2,2,3
54654,Red Rock,3083,Red Rock,1.2,2,2,2,2,4

In [15]:
n_ids = data['유저'].value_counts() >= 10
n_ids = n_ids[n_ids].index.to_list()
data = data[data['유저'].isin(n_ids)]
print(len(data))

n_rvws = data['맥주이름'].value_counts() >= 10
n_rvws = n_rvws[n_rvws].index.to_list()
data = data[data['맥주이름'].isin(n_rvws)]
print(len(data))

24134
24117

---
### 맥주 유사도 기반 추천